application: dryve-web
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /sitemap.xml
  static_files: static/sitemap.xml
  upload: static/sitemap.xml

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /img
  static_dir: img
  
- url: /admin/.*
  script: admin.app
  login: admin

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: latest
